name = "komorebi-reader-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
account_id = "8b0fed04d32e98c9e7d3890fb4a4057c"

[vars]
ENVIRONMENT = "production"
DEFAULT_VOICE_MODEL = "ja_JP-hira-medium"

# Cloudflare KV Storage Binding
[[kv_namespaces]]
binding = "KV_STORE"
id = "46e3ae35bd0c4d7083d50de83a6d83bc"

# Cloudflare R2 Audio Storage Binding
[[r2_buckets]]
binding = "R2_AUDIO"
bucket_name = "komorebi-reader-audio"
